#ifndef APP_SENSOR_CONFIG_H
#define APP_SENSOR_CONFIG_H

#define SENSOR_PPG_VALID_THRESHOLD       100000UL
#define SENSOR_PPG_GROUP_SAMPLES         150U
#define SENSOR_PPG_GROUP_COUNT           3U
#define SENSOR_PPG_TOTAL_SAMPLES         (SENSOR_PPG_GROUP_SAMPLES * SENSOR_PPG_GROUP_COUNT)

#define SENSOR_ECG_SAMPLE_PERIOD_MS      5U
#define SENSOR_ECG_LEADS_OFF_LOW_RAW     50U
#define SENSOR_ECG_LEADS_OFF_HIGH_RAW    4045U
#define SENSOR_ECG_FILTER_BASELINE_RAW   2048U
#define SENSOR_ECG_FILTER_AVG_SIZE       5U
#define SENSOR_PRESSURE_SAMPLE_PERIOD_MS 20U
#define SENSOR_PPG_SAMPLE_PERIOD_MS      10U

#define SENSOR_ADC_MAX_VALUE             4095U
#define SENSOR_VREF_MV                   3300U
#define SENSOR_PRESSURE_ATM_MV           33U
#define SENSOR_PRESSURE_ATM_MMHG         760U

#endif
